# Generated by Django 6.1.1 on 2026-10-05 22:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Lacteos', 'Lacteos'), ('Carnes', 'Carnes'), ('Salsas', 'Salsas'), ('Verduras', 'Verduras'), ('Empaques', 'Empaques')], max_length=20)),
                ('numero_lote', models.CharField(max_length=30, verbose_name='numero de lote')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('vence', models.DateField(verbose_name='fecha de vencimiento')),
                ('estado_registro', models.CharField(max_length=20)),
                ('motivo_registro', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['vence'],
            },
        ),
    ]
