# Generated by Django 6.1 on 2026-10-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="numero_lote",
            field=models.CharField(max_length=30, verbose_name="número de lote"),
        ),
    ]
