"""
Django settings for miproyecto project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clave ya no vive aca: se lee desde el archivo .env (que no se sube).
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- API (ES3) ---
    'rest_framework',
    'rest_framework.authtoken',   # tabla de tokens de /api/token/
    'drf_spectacular',            # documentacion OpenAPI / Swagger
    # --- aplicacion propia ---
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miproyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'miproyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# La conexion se arma con variables de entorno (.env), no escrita a mano.
# Por defecto queda SQLite, que es lo que pide la unidad y Django ya trae.
# Si manana se cambia a PostgreSQL solo se edita el .env: el codigo no se toca.
DB_ENGINE = config("DB_ENGINE", default="django.db.backends.sqlite3")

if DB_ENGINE.endswith("sqlite3"):
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": BASE_DIR / config("DB_NAME", default="db.sqlite3"),
        }
    }
else:
    # Credenciales fuera del codigo: aca nunca hay usuario ni contrasena.
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Sesiones y login
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "lista"
LOGOUT_REDIRECT_URL = "login"

# La cookie de sesion no se puede leer desde JavaScript y caduca al cerrar
# el navegador. En produccion (DEBUG=False) ademas viaja solo por HTTPS.
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 horas
CSRF_COOKIE_HTTPONLY = False  # el token se lee en el formulario, no en JS
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


# ---------------------------------------------------------------------
# API REST (ES3)
# ---------------------------------------------------------------------
# Este bloque es el default de TODO el proyecto. Una vista puede
# sobreescribirlo, pero el default seguro es que todo pida autenticacion.
#
# Por que token y no sesion: un programa cliente no tiene navegador ni
# guarda cookies. Manda su credencial en la cabecera Authorization en cada
# peticion. Las pantallas HTML de la ES2 siguen usando sesion, que para un
# navegador es lo correcto; por eso SessionAuthentication queda tambien,
# y es lo que permite probar desde la interfaz navegable de DRF.
#
# Se ofrecen dos esquemas de token:
#   - Token  (/api/token/)     simple, no expira. El del guion de la unidad.
#   - JWT    (/api/jwt/)       expira a los 30 min y se refresca. Mas seguro:
#                              un token filtrado deja de servir solo.
#
# PAGE_SIZE 10: la bodega puede tener cientos de lotes y el cliente tipico
# es una pantalla o un lector de codigo de barras. Diez filas es lo que se
# alcanza a mostrar sin pedir mas, y evita que una sola peticion arrastre
# la tabla completa.

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Vida util de los JWT. Corta a proposito: si alguien copia el token de
# una cabecera, en media hora deja de servir y necesita el refresh.
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API de monitoreo de vencimiento de insumos",
    "DESCRIPTION": (
        "API REST sobre el mismo modelo que las pantallas HTML. "
        "El estado del lote no lo manda el cliente: lo calcula la regla "
        "de decision con la fecha de hoy."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Mensajes al usuario (django.contrib.messages)
from django.contrib.messages import constants as mensajes  # noqa: E402

MESSAGE_TAGS = {
    mensajes.DEBUG: "debug",
    mensajes.INFO: "info",
    mensajes.SUCCESS: "exito",
    mensajes.WARNING: "aviso",
    mensajes.ERROR: "error",
}
